server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:bookingdb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches
  endpoint:
    health:
      show-details: always

spring.sql.init.mode: always
spring.jpa.defer-datasource-initialization: true

booking:
  no-show:
    cron: "0 0/15 * * * *"
    cutoff-time: "10:00"
